redis:
  host: ${REDIS_HOST}        # Redis 서버 호스트 (AWS EC2 호스트 이름 또는 IP)
  port: 6379                        # Redis 포트 (기본값: 6379)
  password: ${REDIS_PASSWORD}       # Redis 인증 비밀번호 (없다면 생략 가능)
  timeout: 2000                     # 연결 타임아웃 (ms 단위)
  lettuce:
    pool:
      max-active: 10              # 최대 연결 수
      max-idle: 5                 # 유휴 상태 연결의 최대 수
      min-idle: 1
server:
  port: 8080
spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        ddl-auto: none;
        show-sql: true
        cache:
          use_query_cache: false
          use_second_level_cache: false
          use_structured_entries: false
          use_minimal_puts: false
          region:
            factory_class: org.hibernate.cache.internal.NoCachingRegionFactory
        generate_statistics: false
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}